apiVersion: v1
kind: ConfigMap
metadata:
  name: game-demo
data:             # actual content in key:value pair.
  mongo-url: mongo-service #service name of MongoDB which will be endpoint of MongoDB
